version: "3.8"

services:
  postgresdb:
    image: postgres
    ports:
      - 25432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    volumes:
      - ./db-store:/var/lib/postgresql/data
    restart: unless-stopped
  #   pgadmin:
  #     container_name: container-pgadmin
  #     image: dpage/pgadmin4
  #     depends_on:
  #       - postgresdb
  #     ports:
  #       - "5050:80"
  #     environment:
  #       PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #       PGADMIN_DEFAULT_PASSWORD: root
  #     restart: unless-stopped

  app:
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      DB_HOST: postgresdb
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: todo_db

    depends_on:
      - postgresdb
    links:
      - postgresdb
# volumes:
#   db:
