# API test using Rest client vscode extension

get http://localhost:3000/

###
get http://localhost:3000/tasks

###
post http://localhost:3000/tasks
Content-Type: application/json

{
    "title": "Task 4",
    "completed": false
}

###
put http://localhost:3000/tasks/4
Content-Type: application/json

{
    "title": "Task 1",
    "completed": true
}

###
delete http://localhost:3000/tasks/3

