name: Publish Docker image to GitHub Container Registry
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_IMAGE_TOKEN }}
      - name: Build and push
        run: |
              docker build './4 Prisma PostgreSQL' --tag ghcr.io/suaebahmed/4prisma-postgresql-image:latest
              docker run ghcr.io/suaebahmed/4prisma-postgresql-image:latest
              docker push ghcr.io/suaebahmed/4prisma-postgresql-image:latest