name: Deploy Apps
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch

on:
  workflow_dispatch:
    inputs:
        opt:
          description: Environment
          required: true
          type: choice
          options:
              - 'staging'
              - 'production'
          default: staging

  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string


jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}

  deploy:
    runs-on: ubuntu-latest
    env:
        ENV: ${{ github.event.inputs.opt || 'staging' }}
    steps:
        - name: Check out source repository
          uses: actions/checkout@v3
        - name: Print dispatch inputs opt 
          run: echo inputs opt ${{ github.event.inputs.opt }}

        - name: Print env
          run: echo ENV value is ${{ env.ENV }}

      # - name: App1 - Build And Deploy for Staging
      #   if: ${{ env.ENV == 'staging'}}
      #   uses: Azure/static-web-apps-deploy@v1
      # - run: |
      #     echo "Deploying app1"

      # - name: App2- Build And Deploy for Staging
      #   if: ${{ env.ENV == 'staging'}}
      #   uses: Azure/static-web-apps-deploy@v1
      # - run: |
      #     echo "deploying app2"
